export const LOADING_CHANGED = 'LOADING_CHANGED'
export const SET_PHOTOS_API = 'SET_PHOTOS_API'
export const SET_KEYBOARD_VALUE = 'SET_KEYBOARD_VALUE'
export const SET_ARRAY_HOLDER = 'SET_ARRAY_HOLDER'
