# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'photoGallery' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for photoGallery

  target 'photoGallery-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  end

  target 'photoGalleryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'photoGallery-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for photoGallery-tvOS

  target 'photoGallery-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
